import type { Metadata } from "next";
import { NextUIProvider } from "@nextui-org/system";
import "./globals.css";
import { montserrat } from "./(frontend)/styles/fonts";
import { Toaster } from "../components/ui/toaster";
import { SessionProvider } from "next-auth/react";
import { auth } from "./auth";
import ReactQueryProvider from "./(frontend)/providers/ReactQueryProvider";
import StoreProvider from "./StoreProvider";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import { ClerkProvider } from "@clerk/nextjs";
import { ptPT } from "@clerk/localizations";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <>
      <ClerkProvider localization={ptPT}>
        <html lang="pt">
          <body className={`${montserrat.className} antialiased`}>
            <NextUIProvider>
              <NextThemesProvider
                attribute="class"
                defaultTheme="light"
                // forcedTheme="light"
              >
                <SessionProvider session={session}>
                  <StoreProvider>
                    <ReactQueryProvider>{children}</ReactQueryProvider>
                  </StoreProvider>
                </SessionProvider>
              </NextThemesProvider>
            </NextUIProvider>
            <Toaster />
          </body>
        </html>
      </ClerkProvider>
    </>
  );
}

{
}
